# Generated by Django 4.2 on 2023-09-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_jobpost_company_name_jobpost_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
