# Generated by Django 4.2 on 2023-09-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_jobpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
