# Generated by Django 4.2 on 2023-09-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_jobpost_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('skill', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
