# Generated by Django 4.2 on 2023-09-12 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_skill_jobpost_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsearch',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='date',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobsearch',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='mode',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='applicant_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='certification',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='college_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='job_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.jobpost'),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='qualification',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobsearch',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
    ]
