# Generated by Django 4.2 on 2023-09-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_jobsearch_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Education',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
