# Generated by Django 4.2 on 2023-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_jobpost_applied_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date',
            field=models.DateField(),
        ),
    ]
