# Generated by Django 4.2.5 on 2023-10-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_jobpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Education',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
