# Generated by Django 4.2.5 on 2023-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_jobpost_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
