# Generated by Django 4.2.5 on 2023-10-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_jobpost_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
