# Generated by Django 4.2.5 on 2023-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_jobpost_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='d_day',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='d_exp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='d_req',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='d_res',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='d_time',
            field=models.TextField(null=True),
        ),
    ]
