# Generated by Django 4.2.5 on 2023-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_jobpost_d_day_jobpost_d_exp_jobpost_d_req_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='date',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='d_day',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='Education',
            new_name='education_required',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='d_exp',
            new_name='employment_type',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='d_req',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='mode',
            new_name='mode_of_working',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='d_res',
            new_name='required_skills',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='d_time',
            new_name='requirements',
        ),
        migrations.RenameField(
            model_name='jobpost',
            old_name='desc',
            new_name='responsibilities',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='no_of_positions',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='work_time',
            field=models.TextField(null=True),
        ),
    ]
