# Generated by Django 4.2.5 on 2023-10-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_rename_work_time_jobpost_shift_and_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='description',
            new_name='about_the_job',
        ),
    ]
