# Generated by Django 4.2.5 on 2023-11-01 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
