# Generated by Django 4.2.5 on 2023-12-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_jobpost_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_posted',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
